// "use client";
import { Button } from "@/components/ui/button";

export const metadata = {
    title: "Dashboard",
    description: "Generated by AR-Soft team",
};
const Dashboard = () => {
  return (
      <div>
            Dashboard
      </div>
  );
};

export default Dashboard;
